FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /usr/src/app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

RUN mkdir -p /app_output && \
    cp -r target/azure-functions/*/* /app_output/

# Estágio 2: Runtime
FROM mcr.microsoft.com/azure-functions/java:4-java17
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=build /app_output /home/site/wwwroot